"""initial schema

Revision ID: 95f212b7d745
Revises: b0ad6e9d7fd7
Create Date: 2026-03-08 11:03:15.022856+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95f212b7d745'
down_revision: Union[str, Sequence[str], None] = 'b0ad6e9d7fd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###