"""add traveler type to travelers

Revision ID: 9a0a2e2fd565
Revises: c70f90e14695
Create Date: 2026-03-08 20:13:29.717632+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a0a2e2fd565'
down_revision: Union[str, Sequence[str], None] = 'c70f90e14695'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('adult', 'child', 'infant', name='traveler_type_for_booking').create(op.get_bind())
    op.add_column('travelers', sa.Column('traveler_type', postgresql.ENUM('adult', 'child', 'infant', name='traveler_type_for_booking', create_type=False), nullable=False))
    op.sync_enum_values(
        enum_schema='public',
        enum_name='booking_item_type',
        new_values=['flight', 'hotel', 'tour', 'package'],
        affected_columns=[TableReference(table_schema='public', table_name='booking_items', column_name='item_type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='booking_item_type',
        new_values=['flight', 'hotel', 'package'],
        affected_columns=[TableReference(table_schema='public', table_name='booking_items', column_name='item_type')],
        enum_values_to_rename=[],
    )
    op.drop_column('travelers', 'traveler_type')
    sa.Enum('adult', 'child', 'infant', name='traveler_type_for_booking').drop(op.get_bind())
    # ### end Alembic commands ###