"""add traveler and support traveler document attach

Revision ID: a56ea8edb0bb
Revises: 9a0a2e2fd565
Create Date: 2026-03-09 12:54:13.620081+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a56ea8edb0bb'
down_revision: Union[str, Sequence[str], None] = '9a0a2e2fd565'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###