"""add payment idempotecy key

Revision ID: beff523ca153
Revises: 95f212b7d745
Create Date: 2026-03-08 16:03:35.145840+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beff523ca153'
down_revision: Union[str, Sequence[str], None] = '95f212b7d745'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('idempotency_key', sa.String(length=255), nullable=True))
    op.create_index('idx_payments_idempotency_key', 'payments', ['idempotency_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_payments_idempotency_key', table_name='payments')
    op.drop_column('payments', 'idempotency_key')
    # ### end Alembic commands ###