export type PageCategory =
  | 'Public'
  | 'Auth'
  | 'Checkout'
  | 'Account'
  | 'Admin'
  | 'System'

export type StitchPageDefinition = {
  category: PageCategory
  description: string
  href: string
  path: string
  slug: string
  source: string
  title: string
}

const stitchSource = (slug: string) => `/stitch-page/${slug}/code.html`

const definePage = (
  category: PageCategory,
  title: string,
  path: string,
  href: string,
  slug: string,
  description: string,
): StitchPageDefinition => ({
  category,
  description,
  href,
  path,
  slug,
  source: stitchSource(slug),
  title,
})

export const stitchPages = {
  home: definePage(
    'Public',
    'Home',
    '/',
    '/',
    'travelbook_home_page_official_final_cleaned',
    'Landing page chính của TravelBook.',
  ),
  tours: definePage(
    'Public',
    'Tours',
    '/tours',
    '/tours',
    'travelbook_tours_catalog_final_official_cleaned',
    'Trang catalog tour.',
  ),
  tourDetail: definePage(
    'Public',
    'Tour Detail',
    '/tours/:tourId',
    '/tours/amalfi-coast-sailing',
    'tour_detail_amalfi_coast_sailing_final_cleaned',
    'Trang chi tiết tour mẫu.',
  ),
  tourSchedules: definePage(
    'Public',
    'Tour Schedules',
    '/tours/:tourId/schedules',
    '/tours/amalfi-coast-sailing/schedules',
    'travelbook_tour_schedules_final_official_cleaned',
    'Trang lịch khởi hành của tour.',
  ),
  destinations: definePage(
    'Public',
    'Destinations',
    '/destinations',
    '/destinations',
    'travelbook_destinations_final_official_cleaned',
    'Trang khám phá điểm đến.',
  ),
  promotions: definePage(
    'Public',
    'Promotions',
    '/promotions',
    '/promotions',
    'travelbook_promotions_final_official_cleaned',
    'Trang khuyến mãi.',
  ),
  helpCenter: definePage(
    'Public',
    'Help Center',
    '/help',
    '/help',
    'travelbook_help_support',
    'Trang hỗ trợ public.',
  ),
  login: definePage(
    'Auth',
    'Login',
    '/login',
    '/login',
    'travelbook_login',
    'Trang đăng nhập.',
  ),
  register: definePage(
    'Auth',
    'Register',
    '/register',
    '/register',
    'travelbook_register',
    'Trang đăng ký.',
  ),
  forgotPassword: definePage(
    'Auth',
    'Forgot Password',
    '/forgot-password',
    '/forgot-password',
    'travelbook_forgot_password_official_final_cleaned',
    'Trang quên mật khẩu.',
  ),
  resetPassword: definePage(
    'Auth',
    'Reset Password',
    '/reset-password',
    '/reset-password',
    'travelbook_reset_password',
    'Trang đặt lại mật khẩu.',
  ),
  checkoutReview: definePage(
    'Checkout',
    'Checkout Review',
    '/checkout/tours/:tourId',
    '/checkout/tours/amalfi-coast-sailing',
    'travelbook_checkout_review_final_cleaned',
    'Trang rà soát đơn checkout.',
  ),
  payment: definePage(
    'Checkout',
    'Payment',
    '/checkout/payment',
    '/checkout/payment',
    'travelbook_payment_final_cleaned',
    'Trang thanh toán.',
  ),
  paymentSuccess: definePage(
    'Checkout',
    'Payment Success',
    '/checkout/success/:bookingId',
    '/checkout/success/TBK-2048',
    'travelbook_payment_success_final_cleaned',
    'Trang thanh toán thành công.',
  ),
  paymentFailed: definePage(
    'Checkout',
    'Payment Failed',
    '/checkout/failed',
    '/checkout/failed',
    'travelbook_payment_failed_final_cleaned',
    'Trang thanh toán thất bại.',
  ),
  accountDashboard: definePage(
    'Account',
    'Dashboard',
    '/account',
    '/account',
    'travelbook_account_dashboard_official_final_cleaned',
    'Dashboard tài khoản.',
  ),
  profile: definePage(
    'Account',
    'Profile',
    '/account/profile',
    '/account/profile',
    'travelbook_profile_official_final_cleaned',
    'Trang hồ sơ cá nhân.',
  ),
  travelers: definePage(
    'Account',
    'Travelers',
    '/account/travelers',
    '/account/travelers',
    'travelers_management',
    'Trang quản lý travelers.',
  ),
  bookings: definePage(
    'Account',
    'Bookings',
    '/account/bookings',
    '/account/bookings',
    'travelbook_bookings_official_final_cleaned',
    'Trang danh sách booking.',
  ),
  bookingDetail: definePage(
    'Account',
    'Booking Detail',
    '/account/bookings/:bookingId',
    '/account/bookings/TBK-2048',
    'travelbook_booking_detail_final_cleaned',
    'Trang chi tiết booking.',
  ),
  vouchers: definePage(
    'Account',
    'Vouchers',
    '/account/vouchers',
    '/account/vouchers',
    'travelbook_vouchers_official_final_cleaned',
    'Trang voucher.',
  ),
  documents: definePage(
    'Account',
    'Documents',
    '/account/documents',
    '/account/documents',
    'travelbook_documents_official_final_cleaned',
    'Trang documents.',
  ),
  refunds: definePage(
    'Account',
    'Refunds',
    '/account/refunds',
    '/account/refunds',
    'travelbook_refunds_final_official_cleaned',
    'Trang hoàn tiền.',
  ),
  refundDetail: definePage(
    'Account',
    'Refund Detail',
    '/account/refunds/:refundId',
    '/account/refunds/RFD-1120',
    'travelbook_refund_detail_final_official_cleaned',
    'Trang chi tiết refund.',
  ),
  notifications: definePage(
    'Account',
    'Notifications',
    '/account/notifications',
    '/account/notifications',
    'travelbook_notifications_official_final_cleaned_v2',
    'Trang thông báo.',
  ),
  support: definePage(
    'Account',
    'Support',
    '/account/support',
    '/account/support',
    'travelbook_support_final_official_cleaned',
    'Trang hỗ trợ tài khoản.',
  ),
  adminDashboard: definePage(
    'Admin',
    'Admin Dashboard',
    '/admin',
    '/admin',
    'travelbook_admin_dashboard_final_official_cleaned',
    'Dashboard quản trị.',
  ),
  adminTours: definePage(
    'Admin',
    'Tours Management',
    '/admin/tours',
    '/admin/tours',
    'travelbook_tours_management_final_official_cleaned_v3',
    'Trang quản lý tour.',
  ),
  adminBookings: definePage(
    'Admin',
    'Bookings Management',
    '/admin/bookings',
    '/admin/bookings',
    'travelbook_admin_bookings_final_official_reference',
    'Trang quản lý booking admin.',
  ),
  adminDocuments: definePage(
    'Admin',
    'Documents Review',
    '/admin/documents',
    '/admin/documents',
    'travelbook_admin_documents_final_refined_reference',
    'Trang review documents.',
  ),
  adminRefunds: definePage(
    'Admin',
    'Refunds Management',
    '/admin/refunds',
    '/admin/refunds',
    'travelbook_admin_refunds_final_official_reference',
    'Trang quản lý refunds admin.',
  ),
  adminSchedules: definePage(
    'Admin',
    'Schedules Management',
    '/admin/schedules',
    '/admin/schedules',
    'travelbook_schedules_management_final_polished_reference_v2',
    'Trang quản lý schedules.',
  ),
  adminPricing: definePage(
    'Admin',
    'Pricing Management',
    '/admin/pricing',
    '/admin/pricing',
    'travelbook_pricing_management_final_polished_reference',
    'Trang quản lý pricing.',
  ),
  adminOperations: definePage(
    'Admin',
    'Operations Hub',
    '/admin/operations',
    '/admin/operations',
    'operations_hub_travelbook_admin_final_reference',
    'Trang điều hành admin.',
  ),
  notFound: definePage(
    'System',
    '404 Page',
    '/404',
    '/404',
    'travelbook_404_page_final_cleaned',
    'Trang lỗi 404.',
  ),
  serverError: definePage(
    'System',
    '500 Page',
    '/500',
    '/500',
    '500_server_error_travelbook_official_final_cleaned',
    'Trang lỗi 500.',
  ),
} as const

export const categoryOrder: PageCategory[] = [
  'Public',
  'Auth',
  'Checkout',
  'Account',
  'Admin',
  'System',
]

export const pageDirectoryItems: StitchPageDefinition[] = [
  stitchPages.home,
  stitchPages.tours,
  stitchPages.tourDetail,
  stitchPages.tourSchedules,
  stitchPages.destinations,
  stitchPages.promotions,
  stitchPages.helpCenter,
  stitchPages.login,
  stitchPages.register,
  stitchPages.forgotPassword,
  stitchPages.resetPassword,
  stitchPages.checkoutReview,
  stitchPages.payment,
  stitchPages.paymentSuccess,
  stitchPages.paymentFailed,
  stitchPages.accountDashboard,
  stitchPages.profile,
  stitchPages.travelers,
  stitchPages.bookings,
  stitchPages.bookingDetail,
  stitchPages.vouchers,
  stitchPages.documents,
  stitchPages.refunds,
  stitchPages.refundDetail,
  stitchPages.notifications,
  stitchPages.support,
  stitchPages.adminDashboard,
  stitchPages.adminTours,
  stitchPages.adminBookings,
  stitchPages.adminDocuments,
  stitchPages.adminRefunds,
  stitchPages.adminSchedules,
  stitchPages.adminPricing,
  stitchPages.adminOperations,
  stitchPages.notFound,
  stitchPages.serverError,
]
