"""add booking cancellation and refunds

Revision ID: 20044e5dc351
Revises: a56ea8edb0bb
Create Date: 2026-03-09 15:27:14.916113+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20044e5dc351'
down_revision: Union[str, Sequence[str], None] = 'a56ea8edb0bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('pending', 'processed', 'failed', 'cancelled', name='refund_status').create(op.get_bind())
    op.create_table('refunds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'processed', 'failed', 'cancelled', name='refund_status', create_type=False), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.sync_enum_values(
        enum_schema='public',
        enum_name='traveler_document_type',
        new_values=['passport', 'visa', 'national_id', 'invoice', 'voucher', 'other'],
        affected_columns=[TableReference(table_schema='public', table_name='travelers', column_name='document_type')],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema='public',
        enum_name='document_type',
        new_values=['passport', 'visa', 'national_id', 'invoice', 'voucher', 'other'],
        affected_columns=[TableReference(table_schema='public', table_name='uploaded_documents', column_name='document_type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='document_type',
        new_values=['passport', 'visa', 'national_id', 'invoice', 'other'],
        affected_columns=[TableReference(table_schema='public', table_name='uploaded_documents', column_name='document_type')],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema='public',
        enum_name='traveler_document_type',
        new_values=['passport', 'visa', 'national_id', 'invoice', 'other'],
        affected_columns=[TableReference(table_schema='public', table_name='travelers', column_name='document_type')],
        enum_values_to_rename=[],
    )
    op.drop_table('refunds')
    sa.Enum('pending', 'processed', 'failed', 'cancelled', name='refund_status').drop(op.get_bind())
    # ### end Alembic commands ###